# Generated by Django 4.1.5 on 2023-01-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('ipAddress', models.GenericIPAddressField()),
                ('time', models.TimeField()),
                ('unresolved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('floor', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='room_images')),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('availability', models.BooleanField()),
                ('visitCount', models.IntegerField(default=0)),
            ],
        ),
    ]
