# Generated by Django 4.1.4 on 2023-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lastUpdated',
            field=models.DateField(auto_now=True),
        ),
    ]
