# Generated by Django 4.1.4 on 2023-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='room_images'),
        ),
    ]
