# Generated by Django 4.1.5 on 2023-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_room_availability_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to='room_images'),
        ),
    ]
