# Generated by Django 4.1.5 on 2023-01-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='room_images/placeholder.png', upload_to='room_images'),
        ),
    ]
